from django.db import models


# Create your models here.
class Staff(models.Model):
    cn = models.CharField(max_length=20, null=True, blank=True)
    en = models.CharField(max_length=20, null=True, blank=True)
    jp = models.CharField(max_length=30, null=True, blank=True)
    sex = models.CharField(max_length=4, null=True, blank=True)
    birthplace = models.CharField(max_length=10, null=True, blank=True)
    nation = models.CharField(max_length=10, null=True, blank=True)
    tag = models.CharField(max_length=24, null=True, blank=True)
    race = models.CharField(max_length=50, null=True, blank=True)
    rarity = models.CharField(max_length=1, null=True, blank=True)
    profession = models.CharField(max_length=5, null=True, blank=True)
    approach = models.CharField(max_length=50, null=True, blank=True)
    camp = models.CharField(max_length=20, null=True, blank=True)
    team = models.CharField(max_length=20, null=True, blank=True)
    des = models.CharField(max_length=200, null=True, blank=True)
    feature = models.CharField(max_length=500, null=True, blank=True)
    str_s = models.CharField(max_length=4, null=True, blank=True)
    flex = models.CharField(max_length=4, null=True, blank=True)
    tolerance = models.CharField(max_length=4, null=True, blank=True)
    plan = models.CharField(max_length=4, null=True, blank=True)
    skill = models.CharField(max_length=4, null=True, blank=True)
    adapt = models.CharField(max_length=4, null=True, blank=True)
    moredes = models.CharField(max_length=20, null=True, blank=True)
    icon = models.CharField(max_length=500, null=True, blank=True)
    half = models.CharField(max_length=900, null=True, blank=True)
    ori_hp = models.CharField(max_length=10, null=True, blank=True)
    ori_atk = models.IntegerField(default=0, null=True, blank=True)
    ori_def = models.IntegerField(default=0, null=True, blank=True)
    ori_res = models.IntegerField(default=0, null=True, blank=True)
    ori_dt = models.CharField(max_length=5, null=True, blank=True)
    ori_dc = models.IntegerField(default=0, null=True, blank=True)
    ori_block = models.IntegerField(default=0, null=True, blank=True)
    ori_cd = models.CharField(max_length=20, null=True, blank=True)
    index = models.CharField(max_length=10, null=True, blank=True)
    sort_id = models.IntegerField(default=0, null=True, blank=True)

